### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by pndwal** [mywalkb/DenylistUnmount#1]
In How to use, do you mean "Disable enforce denylist'?

**Comment by mywalkb** [comment]
Mean: "Enforce denylist" must be disabled.
![IMG_20220605_143527](https://user-images.githubusercontent.com/66966897/172050810-12025a16-8c96-4cfe-b3f4-09089890d0a9.jpg)
So magisk load module in app with zygisk and the module force the unmount of magisk in app, if it is in deny list.
Use the same mechanism of shamiko. I don't know how shamiko hide magisk, in my module I used a very simple mode and works for many apps.

**Comment by pndwal** [comment]
Clearly!

So typo remains! 🤪

![IMG_20220606_020046](https://user-images.githubusercontent.com/35104473/172059465-7d935c31-c986-409b-bc93-6516d23fd205.jpg)

**Comment by mywalkb** [comment]
> So typo remains! zany_face

Sorry I did not understand, now is fixed, thanks

**Comment by pndwal** [comment]
> ...Use the same mechanism of shamiko. I don't know how shamiko hide magisk, in my module I used a very simple mode and works for many apps.

I don't know either.

But I responded to a user of your module here:
https://forum.xda-developers.com/t/discussion-magisk-the-age-of-zygisk.4393877/post-86985283

Please read Canyie's Riru-MomoHider main page (I linked) if you haven't already... much of Shamiko hiding is repurposed from her original open source MomoHider, so commits there should be useful...

Nice work here by the way! Hope you are able to incorporate some of the more challenging hiding mechanisms in time... 👍 PW

**Comment by mywalkb** [comment]
> ! Hope you are able to incorporate some of the more challenging hiding mechanisms in time... 

My first idea was porting MomoHider to zygisk, after seeing SafetyNetFix, my first version is a simple unmount performed by magisk.
