### ISSUE TITLE
0.3 Fails to Load

### ISSUE THREAD

**Issue by brackenhill-mob** [mywalkb/DenylistUnmount#4]
Reports

"Zygisk module not loaded due to incompatibility"

Using Magisk v24.3

FWIW Shamiko v0.51 works (I found DenylistUnmount because 0.5 caused some of my apps to misbehave

**Comment by mywalkb** [comment]
Could you post logcat? Version 0.2 works?

**Comment by brackenhill-mob** [comment]
Sure. What am I searching for? Everything for Magisk? DenylistUnmount doesn't show up in the log

**Comment by mywalkb** [comment]
Version 0.3 introduce a new feature "whitelist based" developed by @HuskyDG so for now as temporary solution you can rollback to 0.2 or use shamiko if works.

> Everything for Magisk?

If you can post magisk's log is better.
Could give more informations on your environment? android version and rom.

**Comment by HuskyDG** [comment]
That's weird, denylist v0.3 is working fine for me

**Comment by mywalkb** [comment]
Sure also on my devices is working fine.
Maybe symbols strcmp or system_get_property are not resolved.

**Comment by brackenhill-mob** [comment]
my setup is Xiaomi POCO X3 NFC (aka Surya) running ArrowOS 12.1 with Magisk 24.1

Attached is an edited logcat. I stopped once the messages were 10 minutes apart

HTH
[logcat_06-30-2022_14-10-42.txt](https://github.com/mywalkb/DenylistUnmount/files/9027716/logcat_06-30-2022_14-10-42.txt)

**Comment by brackenhill-mob** [comment]
Oh and v0.2 worked perfectly on this same setup ;)

**Comment by mywalkb** [comment]
I tested on an emulator android 12 and works.

Shamiko use 
```
allow zygote unlabeled file { open read getattr }
allow zygote zygote capability sys_chroot
```
so solution with file should be good. 
https://github.com/LSPosed/LSPosed/discussions/1684

**Comment by mywalkb** [comment]
@brackenhill-mob could you test this debug version?
[denylist-v0.3.zip](https://github.com/mywalkb/DenylistUnmount/files/9031251/denylist-v0.3.zip)

This version use stat on file whitelist
```
    void preSpecialize(std::string process) {
        struct stat whitelist;
        bool whitelist_mode = false;
        uint32_t flags = api->getFlags();

        if (stat(WHITELIST_FILE, &whitelist) == 0) {
            whitelist_mode = true;
            LOGD("Whitelist mode");
        }

        if ((flags & zygisk::PROCESS_ON_DENYLIST) != 0 ||
            (whitelist_mode && (flags & zygisk::PROCESS_GRANTED_ROOT) == 0)) {
            api->setOption(zygisk::FORCE_DENYLIST_UNMOUNT);
        }
        api->setOption(zygisk::DLCLOSE_MODULE_LIBRARY);
    }
```
If you want test the whitelist mode just touch file `/data/adb/modules/denylist_unmount/whitelist`

**Comment by brackenhill-mob** [comment]
This one works ;)

What do we put in the whitelist file? The internal name of the app?

Whitelisting seems to make more sense to me than denylist. Am I correct that if I use it, I can remove everything from/forget about denylist?

**Comment by mywalkb** [comment]
> What do we put in the whitelist file?

nothing. When the file exist, all apps except granted root unmount magisk.

>  I can remove everything from/forget about denylist?

Yes. Remove all apps and create empty file whitelist so only granted root apps see magisk, all other can't access to it.

**Comment by mywalkb** [comment]
I installed Arrow OS 12.1 on my xiaomi device and I tested previous version 0.3 and works. 
You had a very particular situation. Good to know that now works.
I will going to release version 0.4 for this fix

**Comment by brackenhill-mob** [comment]
> > What do we put in the whitelist file?
> 
> nothing. When the file exist, all apps except granted root unmount magisk.

Simples ;)

> > I can remove everything from/forget about denylist?
> 
> Yes. Remove all apps and create empty file whitelist so only granted root apps see magisk, all other can't access to it.

Might be worth adding this to the README.md

**Comment by mywalkb** [comment]
> Might be worth adding this to the README.md

Sure, I will update README with all instructions
