### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by vmdao** [mywalkb/DenylistUnmount#5]
Hi Bro,
I rebuild successful new version. But I when flash it show error: "! Failed to verify customize.sh"
P/s:
Installation environment: MacOS 15 
I have compare old zip file (vesion 0.4) and new zip file (version 0.41) size is diffrent 
Here is log file. 

Do you have idea?
Thank you very much!
[magisk_install_log_2022-09-24T09.45.09.log](https://github.com/mywalkb/DenylistUnmount/files/9637762/magisk_install_log_2022-09-24T09.45.09.log)

**Comment by mywalkb** [comment]
Hi, have you executed ./build.sh for build?
If you change files without execute build.sh sha256 is not updated, so installation fails.
You should change file in directory magisk and execute build.sh for new zip. 
It require NDK and ndk-build must be in your PATH.

**Comment by vmdao** [comment]
Thank for your reply..
I used to build.sh, result created  denylist-v04.zip



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mywalkb** [comment]
Could you attach the result zip? 
build.sh is developed in linux environment maybe on MacOS there is something difference.

**Comment by alezzigo** [comment]
Yes, there
[denylist-v0.4.zip](https://github.com/mywalkb/DenylistUnmount/files/9638896/denylist-v0.4.zip)

**Comment by mywalkb** [comment]
Could you verify if in you MacOS there is the command sha256sum? 
I have MacOS 10.14 and the command doesn't exist but there is shasum -a 256, if this is the issue is easy to fix.

**Comment by vmdao** [comment]
Yes. I will try it.
Thank you so much!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mywalkb** [comment]
I tested your zip in my environment and works, so MacOS can build zip without issues.
Release zip works for you? Maybe the attached zip is wrong.
In your log the name is denylist-v0.41.zip while the attached zip is denylist-v0.4.zip.

**Comment by vmdao** [comment]
Yes. I build with origin source code version 0.4(not change) to test build.sh.
Now I prepare linux os build again.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mywalkb** [comment]
Could you test this [build.zip](https://github.com/mywalkb/DenylistUnmount/files/9648639/build.zip) ?
I tested on github actions and works. Is not MacOS 15 but is 11.2.

**Comment by mywalkb** [comment]
> MacOS 15

Sorry, but I have a doubt on this version.
I don't follow MacOS versioning much, so I was convinced that Apple had arrived at MacOS 15.0, while I saw that the latest version is MacOS 13, so by 15 you mean 10.15 (Catalina)?
